project:
  type: website

website:
  title: "Live Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: example.pdf
        text: CV

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
