project:
  type: website

website:
  title: "Prepped Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog/index.qmd
        text: blog

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
